"""Install / uninstall / doctor the DeepSeek Harness `poe-bd` agent preset.

The repo keeps the preset template under `dsh/agent-presets/poe-bd/` (source of
truth, regenerated by `scripts/adapt_skills_for_dsh.py`). This installer copies
it into the user-authored preset root that DSH's roster scans:

    ${DSH_HOME:-$HOME/.dsh}/.agent-presets/poe-bd/

It never touches the shipped preset install or the host composition. Layer-1
MCP registration is a separate opt-in (`dsh web --patch dsh/poe-bd.mcp.cordis.yml`),
printed as a next step.

Usage (from the repo root):

    python scripts/install_dsh_preset.py install            # install (dry-run: --dry-run)
    python scripts/install_dsh_preset.py install --repo-root E:/other/poe-bd-creator
    python scripts/install_dsh_preset.py uninstall
    python scripts/install_dsh_preset.py doctor
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PRESET = ROOT / "dsh" / "agent-presets" / "poe-bd"
PATCH_FILE = ROOT / "dsh" / "poe-bd.mcp.cordis.yml"
PRESET_ID = "poe-bd"
REQUIRED_SKILLS = (
    "poe-bd-create",
    "poe-bd-learn",
    "poe-bd-learning-loop",
    "poe-bd-research",
    "poe-bd-research-worker",
)
# Literal fallback root baked into the checked-in compositions; rewritten at
# install time when --repo-root differs.
DEFAULT_ROOT_LITERAL = "E:/poe-bd-creator"
_ROOT_LITERAL_RE = re.compile(re.escape(DEFAULT_ROOT_LITERAL))


def dsh_home(environ: dict[str, str]) -> Path:
    return Path(environ.get("DSH_HOME") or Path.home() / ".dsh")


def preset_target(dsh_home_dir: Path) -> Path:
    return dsh_home_dir / ".agent-presets" / PRESET_ID


def source_problems(source: Path) -> list[str]:
    problems: list[str] = []
    for rel in ("agent.cordis.yml", "preset.yml"):
        if not (source / rel).is_file():
            problems.append(f"missing {rel}")
    for skill in REQUIRED_SKILLS:
        if not (source / "skills" / skill / "SKILL.md").is_file():
            problems.append(f"missing skills/{skill}/SKILL.md")
    return problems


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def install_preset(
    *,
    source: Path,
    target: Path,
    repo_root: str | None,
    dry_run: bool = False,
) -> dict[str, object]:
    problems = source_problems(source)
    if problems:
        return {"status": "error", "errorCode": "incomplete_source", "problems": problems}
    target_exists = target.exists()
    if target_exists and not (target / "agent.cordis.yml").is_file():
        return {
            "status": "conflict",
            "errorCode": "target_occupied_by_foreign_dir",
            "target": str(target),
        }
    backup_path = target.with_name(f"{target.name}.bak")
    backup = backup_path if target_exists else None
    staging = target.with_name(f"{target.name}.next")
    if staging.exists():
        return {
            "status": "conflict",
            "errorCode": "staging_already_exists",
            "target": str(target),
            "staging": str(staging),
        }
    if backup_path.exists():
        return {
            "status": "conflict",
            "errorCode": ("backup_already_exists" if target_exists else "orphan_backup_exists"),
            "target": str(target),
            "backup": str(backup_path),
        }
    if dry_run:
        return {
            "status": "would_install",
            "target": str(target),
            "backup": str(backup) if backup else None,
            "patchCommand": f"dsh web --patch {PATCH_FILE}",
        }
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        shutil.copytree(source, staging, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        if repo_root is not None and repo_root != DEFAULT_ROOT_LITERAL:
            composition = staging / "agent.cordis.yml"
            rewritten = _ROOT_LITERAL_RE.sub(repo_root.replace("\\", "/"), _read(composition))
            composition.write_text(rewritten, encoding="utf-8", newline="\n")
        staged_problems = source_problems(staging)
        if staged_problems:
            raise RuntimeError("staged preset is incomplete: " + ", ".join(staged_problems))
        if target_exists:
            assert backup is not None
            shutil.move(str(target), str(backup))
            try:
                shutil.move(str(staging), str(target))
            except Exception:
                shutil.move(str(backup), str(target))
                raise
        else:
            shutil.move(str(staging), str(target))
    except Exception as exc:
        if staging.exists():
            shutil.rmtree(staging)
        return {
            "status": "error",
            "errorCode": "install_failed",
            "target": str(target),
            "backup": str(backup) if backup else None,
            "errorKind": type(exc).__name__,
            "detail": str(exc),
        }
    return {
        "status": "installed",
        "target": str(target),
        "backup": str(backup) if backup else None,
        "patchCommand": f"dsh web --patch {PATCH_FILE}",
        "hint": "新建会话时在预设列表选择 poe-bd；或先执行 patchCommand 注册 MCP 工具",
    }


def uninstall_preset(*, target: Path, dry_run: bool = False) -> dict[str, object]:
    if not target.exists():
        return {"status": "not_installed", "target": str(target)}
    if not (target / "agent.cordis.yml").is_file() or not (target / "preset.yml").is_file():
        return {
            "status": "conflict",
            "errorCode": "not_our_preset_dir",
            "target": str(target),
        }
    if dry_run:
        return {"status": "would_remove", "target": str(target)}
    shutil.rmtree(target)
    return {"status": "removed", "target": str(target)}


def doctor_preset(*, source: Path, target: Path) -> dict[str, object]:
    checks: dict[str, bool] = {
        "sourceComplete": not source_problems(source),
        "installed": (target / "agent.cordis.yml").is_file(),
        "skillsInstalled": all(
            (target / "skills" / skill / "SKILL.md").is_file() for skill in REQUIRED_SKILLS
        ),
        "patchExists": PATCH_FILE.is_file(),
    }
    if checks["installed"]:
        try:
            checks["frontmatter"] = all(
                _read(target / "skills" / skill / "SKILL.md").startswith("---")
                for skill in REQUIRED_SKILLS
            )
        except OSError:
            checks["frontmatter"] = False
    # Swap residue detection: `poe-bd.next` is never legitimate after a
    # finished install, and a missing target with a leftover `poe-bd.bak`
    # means a crashed swap that must be restored manually before reinstalling.
    staging = target.with_name(f"{target.name}.next")
    backup = target.with_name(f"{target.name}.bak")
    checks["stagingResidue"] = not staging.exists()
    if not checks["installed"]:
        checks["orphanBackup"] = not backup.exists()
    # A `.bak` beside an installed target is the normal post-reinstall state
    # (the installer keeps the previous version as a recovery point), so it is
    # reported but does not gate the status.
    if backup.exists() and checks["installed"]:
        checks["backupKept"] = True
    gated = {key: value for key, value in checks.items() if key != "backupKept"}
    return {
        "status": "healthy" if all(gated.values()) else "unhealthy",
        "target": str(target),
        "checks": checks,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("install", "uninstall", "doctor"))
    parser.add_argument("--dsh-home", type=Path, help="override DSH_HOME (default env or ~/.dsh)")
    parser.add_argument("--source", type=Path, default=SOURCE_PRESET)
    parser.add_argument("--repo-root", help="repo root to bake into the installed copy")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    home = args.dsh_home or dsh_home(dict(__import__("os").environ))
    target = preset_target(home)
    if args.action == "install":
        result = install_preset(
            source=args.source,
            target=target,
            repo_root=args.repo_root,
            dry_run=args.dry_run,
        )
    elif args.action == "uninstall":
        result = uninstall_preset(target=target, dry_run=args.dry_run)
    else:
        result = doctor_preset(source=args.source, target=target)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return (
        0
        if result["status"]
        in {"installed", "removed", "would_install", "would_remove", "not_installed", "healthy"}
        else 2
    )


if __name__ == "__main__":
    sys.exit(main())
