"""Install / uninstall / doctor the DeepSeek Harness `poe-bd` agent preset.

The repo keeps the preset template under `dsh/agent-presets/poe-bd/` (source of
truth, regenerated by `scripts/adapt_skills_for_dsh.py`). This installer copies
it into the user-authored preset root that DSH's roster scans:

    ${DSH_HOME:-$HOME/.dsh}/.agent-presets/poe-bd/

The shipped preset carries the whole toolset: the three workflows the project
presents to users (research, with an explicit worker; create; learning) plus the
experimental comparative-learning loop driver.

While copying, it fills in the two placeholder tokens the checked-in
compositions carry, so the placed preset needs no environment variables:

    __POE_BD_CREATOR_ROOT__  -> the checkout this installer runs from
                                    (`--repo-root` overrides it)
    __POE_BD_UV__            -> `uv` from PATH, or the checkout's own uv when
                                    PATH has none

It also writes a filled-in copy of the layer-1 MCP patch
(`dsh/poe-bd.mcp.cordis.yml`) beside the preset, for cases where the four
servers are registered host-wide instead of through the preset. Register one or
the other, never both: both start a second MCP client per server (two PoB
engines) and expose the tools to every session.

It never touches the shipped preset install or the host composition.

Usage (from the repo root):

    python scripts/install_dsh_preset.py install            # dry-run: --dry-run
    python scripts/install_dsh_preset.py install --repo-root E:/other/poe-bd-creator
    python scripts/install_dsh_preset.py install --force    # reinstall (rotates the kept .bak)
    python scripts/install_dsh_preset.py uninstall
    python scripts/install_dsh_preset.py doctor
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PRESET = ROOT / "dsh" / "agent-presets" / "poe-bd"
PATCH_FILE = ROOT / "dsh" / "poe-bd.mcp.cordis.yml"
PRESET_ID = "poe-bd"
COMPOSITION_FILE = "agent.cordis.yml"
METADATA_FILE = "preset.yml"
EMITTED_PATCH_NAME = "poe-bd.mcp.cordis.yml"
ROW_SNAPSHOT_FILE = "dsh-plugin-rows.json"
REQUIRED_SKILLS = (
    "poe-bd-create",
    "poe-bd-learn",
    "poe-bd-learning-loop",
    "poe-bd-research",
    "poe-bd-research-worker",
)
# Placeholder tokens the checked-in compositions carry instead of one machine's
# absolute path. `install_preset` must clear every one of them.
ROOT_TOKEN = "__POE_BD_CREATOR_ROOT__"
UV_TOKEN = "__POE_BD_UV__"
TOKEN_PREFIX = "__POE_BD_"
# Literal fallback written by compositions that predate the token rewrite; the
# installer still rewrites it so an edited copy keeps working.
DEFAULT_ROOT_LITERAL = "E:/poe-bd-creator"
_LEGACY_ROOT_LITERAL_RE = re.compile(re.escape(DEFAULT_ROOT_LITERAL))
# A row's plugin name, in the composition's own indentation-tolerant form.
_ROW_NAME_RE = re.compile(r"^\s*-?\s*name:\s*(.+?)\s*$")


def dsh_home(environ: dict[str, str]) -> Path:
    return Path(environ.get("DSH_HOME") or Path.home() / ".dsh")


def preset_target(dsh_home_dir: Path) -> Path:
    return dsh_home_dir / ".agent-presets" / PRESET_ID


def row_names_in(composition: Path) -> set[str]:
    """Every plugin name the composition names, groups included.

    `serverName:` and other keys cannot match: the pattern anchors `name:` right
    after the row's leading whitespace and dash.
    """
    names: set[str] = set()
    for line in _read(composition).splitlines():
        match = _ROW_NAME_RE.match(line)
        if match:
            names.add(match.group(1).strip().strip("'\""))
    return names


def snapshot_row_names(source: Path = SOURCE_PRESET) -> tuple[str, set[str]]:
    """The recorded DSH version and its resolvable row names."""
    path = source / ROW_SNAPSHOT_FILE
    payload = json.loads(_read(path))
    return str(payload.get("dshVersion", "")), {str(name) for name in payload["rowNames"]}


def row_name_problems(source: Path = SOURCE_PRESET) -> list[str]:
    """Rows this preset names that the recorded DSH version cannot resolve.

    A row naming a plugin the running installation does not have makes
    `dsh-agent-presets` report the WHOLE preset broken, which hides it from the
    picker — that is exactly how a row copied from another DSH version breaks a
    mount, so it fails here first. Builtin `cordis:` rows and preset-relative
    rows are not package lookups.
    """
    composition = source / COMPOSITION_FILE
    snapshot = source / ROW_SNAPSHOT_FILE
    if not composition.is_file():
        return [f"{composition}: missing composition"]
    if not snapshot.is_file():
        return [f"{snapshot}: missing row snapshot (regenerate with --write-row-snapshot)"]
    version, known = snapshot_row_names(source)
    problems: list[str] = []
    for name in sorted(row_names_in(composition)):
        if name.startswith("cordis:") or name.startswith(".") or name.startswith("file:"):
            continue
        if name not in known:
            problems.append(
                f"{composition}: row names {name!r}, which DSH {version} does not provide "
                f"(refresh {snapshot.name} after a DSH upgrade, or fix the row)"
            )
    return problems


def resolve_repo_root(explicit: str | None) -> Path:
    """The checkout a placed preset must run from: this one unless overridden."""
    return Path(explicit).resolve() if explicit else ROOT


def resolve_uv(explicit: str | None = None, environ: dict[str, str] | None = None) -> str | None:
    """Resolve the uv executable to bake into a placed composition.

    PATH wins over the checkout's own copy, because the root README requires uv
    as a prerequisite and a fresh clone has no `.tools/` (it is git-ignored).
    Returns None when no uv exists at all.
    """
    env = dict(os.environ) if environ is None else environ
    if explicit:
        return explicit
    if env.get("POE_BD_UV"):
        return env["POE_BD_UV"]
    found = shutil.which("uv")
    if found:
        return found
    for candidate in (ROOT / ".tools" / "uv" / "uv.exe", ROOT / ".tools" / "uv" / "uv"):
        if candidate.is_file():
            return str(candidate)
    return None


def _js_path(value: str) -> str:
    """Render a path for a single-quoted JS literal in the cordis YAML."""
    return value.replace("\\", "/")


def unresolved_tokens(text: str) -> list[str]:
    return sorted({token for token in re.findall(rf"{TOKEN_PREFIX}\w+", text)})


def render_composition(text: str, *, repo_root: Path, uv_literal: str) -> str:
    """Fill the composition's tokens, then any legacy literal checkout path."""
    text = text.replace(ROOT_TOKEN, _js_path(str(repo_root)))
    text = text.replace(UV_TOKEN, _js_path(uv_literal))
    return _LEGACY_ROOT_LITERAL_RE.sub(_js_path(str(repo_root)), text)


def source_problems(source: Path) -> list[str]:
    problems: list[str] = []
    for rel in (COMPOSITION_FILE, METADATA_FILE):
        if not (source / rel).is_file():
            problems.append(f"missing {rel}")
    for skill in REQUIRED_SKILLS:
        if not (source / "skills" / skill / "SKILL.md").is_file():
            problems.append(f"missing skills/{skill}/SKILL.md")
    problems.extend(row_name_problems(source))
    return problems


def template_problems(source: Path) -> list[str]:
    """The checked-in template must carry placeholders, not one machine's path."""
    composition = source / COMPOSITION_FILE
    if not composition.is_file():
        return []
    if TOKEN_PREFIX not in _read(composition):
        return [
            f"{composition} carries none of the {TOKEN_PREFIX}* placeholder tokens; "
            "a placed preset would depend on one machine's absolute path"
        ]
    return []


def write_row_snapshot(dsh_install: Path, *, source: Path = SOURCE_PRESET) -> dict[str, object]:
    """Record the row names a DSH installation provides.

    The union of every `name:` in its shipped presets and bundle patches, plus
    the MCP client the CLI ships for patch layers. Run this after a DSH upgrade.
    """
    manifest = dsh_install / "package.json"
    if not manifest.is_file():
        return {"status": "error", "errorCode": "not_a_dsh_install", "path": str(dsh_install)}
    version = json.loads(_read(manifest)).get("version", "unknown")
    names: set[str] = set()
    sources: list[str] = []
    for pattern in (
        "packages/preset/agent-presets/presets/*/agent.cordis.yml",
        "packages/bundle/*/cordis.patch.yml",
    ):
        for path in sorted(dsh_install.glob(pattern)):
            names |= row_names_in(path)
            sources.append(path.relative_to(dsh_install).as_posix())
    if not names:
        return {"status": "error", "errorCode": "no_rows_found", "path": str(dsh_install)}
    names.add("@deepseek-ai/dsh-mcp-client")
    payload = {
        "dshVersion": version,
        "note": (
            "Resolvable plugin row names for the DSH version above. Regenerate with "
            "`python scripts/install_dsh_preset.py --write-row-snapshot <dsh-checkout>` "
            "after a DSH upgrade."
        ),
        "sources": sources,
        "rowNames": sorted(name for name in names if not name.startswith("cordis:")),
    }
    out = source / ROW_SNAPSHOT_FILE
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"status": "written", "path": str(out), "dshVersion": version,
            "rowNames": len(payload["rowNames"])}


def probe_preset(
    *, dsh_install: Path, target: Path, harness_base: Path | None = None
) -> dict[str, object]:
    """Ask DSH's own preset discovery whether the PLACED preset is mountable.

    Discovery resolves every row's plugin name exactly as the mount does, so its
    verdict is the picker's verdict — the check that catches a row that no schema
    validation would.
    """
    lib = dsh_install / "packages" / "preset" / "agent-presets" / "lib" / "index.js"
    node = shutil.which("node")
    if not lib.is_file() or node is None:
        return {
            "status": "unavailable",
            "reason": (
                "needs a DSH checkout with built libs and node on PATH; "
                f"lib={lib.is_file()} node={node is not None}"
            ),
        }
    base = harness_base or dsh_install / "apps" / "cli"
    script = (
        "import { discoverPresets, SHIPPED_PRESET_ROOT } from "
        f"{json.dumps(lib.as_uri())};\n"
        "import { pathToFileURL } from 'node:url';\n"
        f"const base = pathToFileURL({json.dumps(str(base).replace(chr(92), '/') + '/')}).href;\n"
        "const presets = await discoverPresets([\n"
        "  { path: SHIPPED_PRESET_ROOT, trust: 'system' },\n"
        f"  {{ path: {json.dumps(str(target.parent))}, trust: 'user' }},\n"
        "], base);\n"
        "for (const preset of presets) "
        "console.log(`${preset.id}\\t${preset.broken ?? 'loadable'}`);\n"
    )
    proc = subprocess.run(
        [node, "--input-type=module", "-e", script],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=300,
    )
    verdicts = {}
    for line in proc.stdout.splitlines():
        if "\t" in line:
            preset_id, verdict = line.split("\t", 1)
            verdicts[preset_id.strip()] = verdict.strip()
    if not verdicts:
        return {"status": "error", "detail": (proc.stderr or proc.stdout)[-400:]}
    return {"status": "checked", "preset": PRESET_ID, "verdict": verdicts.get(PRESET_ID, "absent"),
            "all": verdicts}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def install_preset(
    *,
    source: Path,
    target: Path,
    repo_root: str | None,
    uv_command: str | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, object]:
    problems = source_problems(source) + template_problems(source)
    if problems:
        return {"status": "error", "errorCode": "incomplete_source", "problems": problems}
    resolved_root = resolve_repo_root(repo_root)
    target_exists = target.exists()
    if target_exists and not (target / COMPOSITION_FILE).is_file():
        return {
            "status": "conflict",
            "errorCode": "target_occupied_by_foreign_dir",
            "target": str(target),
        }
    backup_path = target.with_name(f"{target.name}.bak")
    backup = backup_path if target_exists else None
    staging = target.with_name(f"{target.name}.next")
    if staging.exists():
        return {
            "status": "conflict",
            "errorCode": "staging_already_exists",
            "target": str(target),
            "staging": str(staging),
        }
    if backup_path.exists():
        # The kept backup is the previous version's recovery point. `--force`
        # rotates it instead of deleting it, so re-installing (the documented
        # update path) stays one command; an orphan backup next to a missing
        # target is still a conflict, because it may be the only good copy.
        if not force or not target_exists:
            return {
                "status": "conflict",
                "errorCode": ("backup_already_exists" if target_exists else "orphan_backup_exists"),
                "target": str(target),
                "backup": str(backup_path),
            }
        rotated_backup = backup_path.with_name(
            f"{backup_path.name}.{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
        )
        if not dry_run:
            shutil.move(str(backup_path), str(rotated_backup))
    else:
        rotated_backup = None
    # uv is resolved after the conflict checks so a pre-existing backup or a
    # staging residue is reported as itself, not masked by a missing tool.
    resolved_uv = resolve_uv(uv_command)
    if resolved_uv is None:
        return {
            "status": "error",
            "errorCode": "uv_not_found",
            "detail": (
                "uv is required to run the poe-bd MCP servers. Install it from "
                "https://docs.astral.sh/uv/ (or pass --uv-command)."
            ),
        }
    emitted_patch = staging / EMITTED_PATCH_NAME
    patch_command = f"dsh web --patch {target / EMITTED_PATCH_NAME}"
    if dry_run:
        return {
            "status": "would_install",
            "target": str(target),
            "backup": str(backup) if backup else None,
            "rotatedBackup": str(rotated_backup) if rotated_backup else None,
            "repoRoot": str(resolved_root),
            "uvCommand": resolved_uv,
            "patchCommand": patch_command,
        }
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        shutil.copytree(source, staging, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        composition = staging / COMPOSITION_FILE
        composition.write_text(
            render_composition(
                _read(composition), repo_root=resolved_root, uv_literal=resolved_uv
            ),
            encoding="utf-8",
            newline="\n",
        )
        if PATCH_FILE.is_file():
            emitted_patch.write_text(
                render_composition(
                    _read(PATCH_FILE), repo_root=resolved_root, uv_literal=resolved_uv
                ),
                encoding="utf-8",
                newline="\n",
            )
        leftovers = unresolved_tokens(_read(composition))
        staged_problems = source_problems(staging)
        if leftovers:
            raise RuntimeError(f"unresolved placeholder tokens in {composition}: {leftovers}")
        if staged_problems:
            raise RuntimeError("staged preset is incomplete: " + ", ".join(staged_problems))
        if target_exists:
            assert backup is not None
            shutil.move(str(target), str(backup))
            try:
                shutil.move(str(staging), str(target))
            except Exception:
                shutil.move(str(backup), str(target))
                raise
        else:
            shutil.move(str(staging), str(target))
    except Exception as exc:
        if staging.exists():
            shutil.rmtree(staging)
        return {
            "status": "error",
            "errorCode": "install_failed",
            "target": str(target),
            "backup": str(backup) if backup else None,
            "rotatedBackup": str(rotated_backup) if rotated_backup else None,
            "errorKind": type(exc).__name__,
            "detail": str(exc),
        }
    return {
        "status": "installed",
        "target": str(target),
        "backup": str(backup) if backup else None,
        "rotatedBackup": str(rotated_backup) if rotated_backup else None,
        "repoRoot": str(resolved_root),
        "uvCommand": resolved_uv,
        "patchCommand": patch_command,
        "hint": (
            "新建 DSH 会话时在预设列表选择 poe-bd；不要同时应用上面的 patch，"
            "否则同一 server 会拉起两套实例"
        ),
    }


def uninstall_preset(*, target: Path, dry_run: bool = False) -> dict[str, object]:
    if not target.exists():
        return {"status": "not_installed", "target": str(target)}
    if not (target / COMPOSITION_FILE).is_file() or not (target / METADATA_FILE).is_file():
        return {
            "status": "conflict",
            "errorCode": "not_our_preset_dir",
            "target": str(target),
        }
    if dry_run:
        return {"status": "would_remove", "target": str(target)}
    shutil.rmtree(target)
    return {"status": "removed", "target": str(target)}


def doctor_preset(*, source: Path, target: Path) -> dict[str, object]:
    uv_literal = resolve_uv()
    checks: dict[str, bool] = {
        "sourceComplete": not (source_problems(source) + template_problems(source)),
        # A row the running DSH cannot resolve hides the preset from the picker,
        # so it is reported here even though only a mount proves the whole tree.
        "rowsResolvable": not row_name_problems(source),
        "installed": (target / COMPOSITION_FILE).is_file(),
        "skillsInstalled": all(
            (target / "skills" / skill / "SKILL.md").is_file() for skill in REQUIRED_SKILLS
        ),
        "patchExists": PATCH_FILE.is_file(),
    }
    if checks["installed"]:
        composition = target / COMPOSITION_FILE
        try:
            checks["frontmatter"] = all(
                _read(target / "skills" / skill / "SKILL.md").startswith("---")
                for skill in REQUIRED_SKILLS
            )
        except OSError:
            checks["frontmatter"] = False
        try:
            checks["tokensResolved"] = not unresolved_tokens(_read(composition))
        except OSError:
            checks["tokensResolved"] = False
        if checks["patchExists"]:
            checks["emittedPatch"] = (target / EMITTED_PATCH_NAME).is_file()
    # Swap residue detection: `poe-bd.next` is never legitimate after a
    # finished install, and a missing target with a leftover `poe-bd.bak`
    # means a crashed swap that must be restored manually before reinstalling.
    staging = target.with_name(f"{target.name}.next")
    backup = target.with_name(f"{target.name}.bak")
    checks["stagingResidue"] = not staging.exists()
    if not checks["installed"]:
        checks["orphanBackup"] = not backup.exists()
    # A `.bak` beside an installed target is the normal post-reinstall state
    # (the installer keeps the previous version as a recovery point), so it is
    # reported but does not gate the status.
    if backup.exists() and checks["installed"]:
        checks["backupKept"] = True
    gated = {key: value for key, value in checks.items() if key != "backupKept"}
    return {
        "status": "healthy" if all(gated.values()) else "unhealthy",
        "target": str(target),
        "checks": checks,
        "uvCommand": uv_literal or "uv (not found: install uv or set POE_BD_UV)",
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action",
        nargs="?",
        choices=("install", "uninstall", "doctor"),
        help="preset action; omitted when --write-row-snapshot or --probe is used",
    )
    parser.add_argument("--dsh-home", type=Path, help="override DSH_HOME (default env or ~/.dsh)")
    parser.add_argument("--source", type=Path, default=SOURCE_PRESET)
    parser.add_argument("--repo-root", help="checkout a placed preset must run from")
    parser.add_argument("--uv-command", help="uv executable to bake into a placed preset")
    parser.add_argument(
        "--force",
        action="store_true",
        help="reinstall over an existing preset by rotating its kept .bak to a timestamped name",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--write-row-snapshot",
        type=Path,
        metavar="DSH_CHECKOUT",
        help="record that DSH installation's resolvable row names into the preset snapshot",
    )
    parser.add_argument(
        "--probe",
        type=Path,
        metavar="DSH_CHECKOUT",
        help="ask that DSH installation's own preset discovery whether the PLACED preset mounts",
    )
    parser.add_argument(
        "--harness-base",
        type=Path,
        help="base the probe resolves plugin names against (default: <DSH_CHECKOUT>/apps/cli)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    home = args.dsh_home or dsh_home(dict(os.environ))
    target = preset_target(home)
    if args.write_row_snapshot is not None:
        result = write_row_snapshot(args.write_row_snapshot, source=args.source)
    elif args.probe is not None:
        result = probe_preset(
            dsh_install=args.probe, target=target, harness_base=args.harness_base
        )
    elif args.action == "install":
        result = install_preset(
            source=args.source,
            target=target,
            repo_root=args.repo_root,
            uv_command=args.uv_command,
            force=args.force,
            dry_run=args.dry_run,
        )
    elif args.action == "uninstall":
        result = uninstall_preset(target=target, dry_run=args.dry_run)
    elif args.action == "doctor":
        result = doctor_preset(source=args.source, target=target)
    else:
        _parser().error("an action is required: install, uninstall or doctor")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if result["status"] == "checked":
        return 0 if result.get("verdict") == "loadable" else 2
    return (
        0
        if result["status"]
        in {
            "installed",
            "removed",
            "would_install",
            "would_remove",
            "not_installed",
            "healthy",
            "written",
        }
        else 2
    )


if __name__ == "__main__":
    sys.exit(main())
